#Check the resource quotas allowed for specific namespace
kubectl describe resourcequotas -n team-platform

Name:            team-platform
Namespace:       team-platform
Resource         Used  Hard
--------         ----  ----
limits.cpu       0     20
limits.memory    0     50Gi
pods             0     20
requests.cpu     0     10
requests.memory  0     20Gi
secrets          0     20
services         0     20

#Check the limit-range configuration that has been applied, allowing us to add default resources/limts quotas to our applications
kubectl describe limitrange -n team-platform

Name:                  team-platform
Namespace:             team-platform
Type                   Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
----                   --------  ---  ---  ---------------  -------------  -----------------------
Pod                    cpu       10m  1    -                -              -
Pod                    memory    4Mi  1Gi  -                -              -
PersistentVolumeClaim  storage   24M  -    -                -              -

#Check the Kubenetes Service Account crated for the team. 
#This service acc can also be used by our applications deployed into this namespace to inherit the IAM permissions associated with the IAM Role associated
#You can see it with the special annotation eks.amazonaws.com/role-arn
kubectl get sa -n team-platform

NAME            SECRETS   AGE
default         0         3d
team-platform   0         3d

kubectl describe sa -n team-platform team-platform

Name:                team-platform
Namespace:           team-platform
Labels:              appName=platform-team-app
                     elbv2.k8s.aws/pod-readiness-gate-inject=enabled
                     projectName=project-platform
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::750860282635:role/team-platform-20231005061338228900000002
                     team: platform
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>

#Check tf state files generated by our apply 
terraform state list module.eks_cluster.module.eks_blueprints_platform_teams

module.eks_cluster.module.eks_blueprints_platform_teams.data.aws_iam_policy_document.admin[0]
module.eks_cluster.module.eks_blueprints_platform_teams.data.aws_iam_policy_document.this[0]
module.eks_cluster.module.eks_blueprints_platform_teams.aws_iam_policy.admin[0]
module.eks_cluster.module.eks_blueprints_platform_teams.aws_iam_role.this[0]
module.eks_cluster.module.eks_blueprints_platform_teams.aws_iam_role_policy_attachment.admin[0]
module.eks_cluster.module.eks_blueprints_platform_teams.kubernetes_limit_range_v1.this["team-platform"]
module.eks_cluster.module.eks_blueprints_platform_teams.kubernetes_namespace_v1.this["team-platform"]
module.eks_cluster.module.eks_blueprints_platform_teams.kubernetes_resource_quota_v1.this["team-platform"]
module.eks_cluster.module.eks_blueprints_platform_teams.kubernetes_service_account_v1.this["team-platform"]

#Check in more detail in the tf state what AWS resouces created with our team module.
terraform state show 'module.eks_cluster.module.eks_blueprints_platform_teams.aws_iam_role.this[0]'

# module.eks_cluster.module.eks_blueprints_platform_teams.aws_iam_role.this[0]:
resource "aws_iam_role" "this" {
    arn                   = "arn:aws:iam::750860282635:role/team-platform-20231005061338228900000002"
    assume_role_policy    = jsonencode(
        {
            Statement = [
                {
                    Action    = "sts:AssumeRole"
                    Effect    = "Allow"
                    Principal = {
                        AWS = "arn:aws:iam::750860282635:user/kube"
                    }
                    Sid       = "AssumeRole"
                },
            ]
            Version   = "2012-10-17"
        }
    )
    create_date           = "2023-10-05T06:13:39Z"
    force_detach_policies = true
    id                    = "team-platform-20231005061338228900000002"
    managed_policy_arns   = [
        "arn:aws:iam::750860282635:policy/team-platform-20231005061338228800000001",
    ]
    max_session_duration  = 3600
    name                  = "team-platform-20231005061338228900000002"
    name_prefix           = "team-platform-"
    path                  = "/"
    tags                  = {
        "Blueprint"  = "eks-blueprint-blue"
        "GithubRepo" = "github.com/aws-ia/terraform-aws-eks-blueprints"
    }
    tags_all              = {
        "Blueprint"  = "eks-blueprint-blue"
        "GithubRepo" = "github.com/aws-ia/terraform-aws-eks-blueprints"
    }
    unique_id             = "AROA25UWCVMFWLKX5GVDY"
}